config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"

end

app/models/pin.rb
# Model for pins
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "450x450>", :thumb => "300x300>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
# pages class to handle views
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pins_controller.rb
# PinsController for my pins
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @pins = Pin.all
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private

  def set_pin
    @pin = Pin.find(params[:id])
  end

  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: 'Not authroized to edit this pin' if @pin.nil?
  end

  def pin_params
    params.require(:pin).permit(:description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_frameworksModal.html.erb
<!-- Modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Frameworks</h4>
      </div>
      <div class="modal-body">
        <li class= "list-group-item">Bootstrap</li>
        <li class= "list-group-item">Ruby on Rails</li>
      </div>
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Gems</h4>
      </div>
      <div class="modal-body">
        <li class= "list-group-item">Devise</li>
        <li class= "list-group-item">Bootstrap SASS</li>
        <li class= "list-group-item">Paperclip - "insert github link"</li>
        <li class= "list-group-item">Amazon Web Services SDK - "insert github link"</li>
        <li class= "list-group-item">jQuery Masonry</li>
      </div>
      <div class="modal-footer">
        <div class="btn-group pull-left">
          <button type="button" class="btn btn-default"><%= link_to fa_icon("github 2x"), "https://github.com/tomengland", :target => "_blank" %></button>
          <button type="button" class="btn btn-default"><%= link_to fa_icon("linkedin 2x"), "http://www.linkedin.com/in/tomengland808", :target => "_blank" %></button>
          <button type="button" class="btn btn-default"><%= link_to fa_icon("twitter 2x"), "https://twitter.com/devtomengland", :target => "_blank" %></button>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= fa_icon "close 2x"%></button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<%= render 'layouts/frameworksModal' %>
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", "#aboutModal", :data => {:toggle=>"modal"} %></li>
      <% if user_signed_in? %>
        <li>
          <%= link_to new_pin_path do %>
            <span class="glyphicon glyphicon-plus"></span> New Pin
          <% end %>
        </li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>


</body>
</html>

app/views/pages/_home.html.erb
<div class ="jumbotron center">
  <h1>Welcome to my app!</h1>
    <p>
      <%= link_to "Log in", new_user_session_path , class:"btn btn-default btn-lg"  %>
      <%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
    </p>
</div>

app/views/pages/home.html.erb
<div class ="jumbotron center">
  <h1>Welcome to my app!</h1>
  <% if user_signed_in? %>
    # do_something You're in!
  <% else %>
    <p>
      <%= link_to "Log in", new_user_session_path , class:"btn btn-default btn-lg"  %>
      <%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
    </p>

  <% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="btn-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Back", root_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:thumb)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.email if pin.user %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= link_to image_tag(@pin.image.url(:medium)), root_path, title: 'Click to go back', 'data-placement' => 'left', rel: :tooltip %>
      </div>
        <div class="panel-body">

  <strong>Description:</strong>
  <p><%= @pin.description %></p>
<% if @pin.user == current_user %>
  <%= link_to edit_pin_path(@pin) do %>
    <span class="glyphicon glyphicon-edit"></span>
    Edit
  <% end %>
<% end %>
        </div>
    </div>
  </div>
</div>